title: TheTransitClock
description: The complete core Java software for TheTransitClock real-time transit information project
show_downloads: false
theme: jekyll-theme-tactile

gems:
  - jekyll-mentions
